### ISSUE TITLE
Please add LICENSE file

### ISSUE THREAD

**Issue by remicollet** [icewind1991/Streams#1]
According to composer.json, this library is licensed under MIT
According to MIT licenses term 

```
 The above copyright notice and this permission notice shall be included in
 all copies or substantial portions of the Software.
```

So, to allow use and distribution of this library, please include a LICENSE file with full text.

**Comment by icewind1991** [comment]
Fixed with 1cca87c499b0a50056468b94479effd5b4b390cb

**Comment by remicollet** [comment]
Thanks

**Comment by remicollet** [comment]
LICENSE is commonly used (english)
LICENCE is used in some other language (fr....)

/me just discover than LICENCE is used in UK...
