### ISSUE TITLE
Bail out if fwrite failed in RetryWrapper

### ISSUE THREAD

**Issue by PVince81** [icewind1991/Streams#3]
See https://github.com/icewind1991/Streams/blob/master/src/RetryWrapper.php#L61

If fwrite returned that 0 bytes were written, bail out instead of staying stuck in an infinite loop.

Can happen when using phpseclib's stream and writing to a read-only folder.

**Comment by icewind1991** [comment]
Fixed by d3620e8dc410c86c2ba55579803679c4e0b289ac
